### ISSUE TITLE
Update proto file to support higher precision

### ISSUE THREAD

**Issue by mattwigway** [mapbox/pygeobuf#21]
The latest [proto file for geobuf](https://github.com/mapbox/geobuf/blob/master/geobuf.proto#L32) uses sint64 for coordinates, but pygeobuf uses sint32. This means that if you have a feature encoded with precision higher than 6 (which admittedly the reference encoder will refuse to do, but nowhere does it say it's not allowed), the coordinates will be read incorrectly on deserialization. I'm using higher precision coordinates as intermediary storage for our [seamless census data extraction tool](https://github.com/conveyal/seamless-census). Six decimal places on geographic coordinates is about 10 cm at the equator, which is not high enough resolution for some applications.

**Comment by sgillies** [comment]
@mattwigway thanks for getting me to update this with respect to the master project.
