### ISSUE TITLE
Python 3.x support

### ISSUE THREAD

**Issue by DaZzz** [mapbox/pygeobuf#22]
I'm using python 3.5, so I wonder if it's possible to use this package with python 3.x.

**Comment by sgillies** [comment]
At the time 1.0.0 was released it was not possible to use this package with Python 3, due to lack of Python 3 support in the protobuf package. Recently, https://pypi.python.org/pypi/protobuf/3.0.0b2 is out and does advertise support for Python 3.4. I haven't tried it yet with pygeobuf. Can you give it a try and report back? I'd appreciate it!

**Comment by DaZzz** [comment]
That's what I'm getting right now:
```shell
➜ python --version
Python 3.5.1

➜ pip install pygeobuf
Collecting pygeobuf
Could not find a version that satisfies the requirement pygeobuf (from versions: )
No matching distribution found for pygeobuf
```

**Comment by sgillies** [comment]
@DaZzz there is only a Python 2 wheel on PyPI: https://pypi.python.org/pypi/geobuf#downloads. For Python 3, will you try

```
pip install -U protobuf --pre
pip install git+https://github.com/mapbox/pygeobuf.git#egg=pygeobuf
```

I'm seeing test failures locally due to 2/3 bytes/string issues, am curious to see whether it works at all with your geobuf files.

**Comment by DaZzz** [comment]
@sgillies awesome! It worked! Now I just wonder why wouldn't you put it on PyPI :)

**Comment by sgillies** [comment]
Thanks for testing. I'll upload a Py3 wheel to PyPI as soon as I fix up the tests.

**Comment by DaZzz** [comment]
Tried to use it with real data and it failed.

```shell
$ geobuf encode < test.json > test.pbf

ERROR:geobuf:Failed. Exception caught
Traceback (most recent call last):
  File "/Users/dazzz/Developer/transport-accessibility/lib/python3.5/site-packages/geobuf/scripts/cli.py", line 56, in encode
    3 if with_z else 2)
  File "/Users/dazzz/Developer/transport-accessibility/lib/python3.5/site-packages/geobuf/__init__.py", line 8, in encode
    return Encoder().encode(*args)
  File "/Users/dazzz/Developer/transport-accessibility/lib/python3.5/site-packages/geobuf/encode.py", line 37, in encode
    elif data_type == 'Feature': self.encode_feature(data.feature, obj)
  File "/Users/dazzz/Developer/transport-accessibility/lib/python3.5/site-packages/geobuf/encode.py", line 54, in encode_feature
    self.encode_properties(feature, feature_json.get('properties'))
  File "/Users/dazzz/Developer/transport-accessibility/lib/python3.5/site-packages/geobuf/encode.py", line 127, in encode_properties
    for key, val in props_json.viewitems():
AttributeError: 'dict' object has no attribute 'viewitems'
```

`test.json` is basically this file https://github.com/mapbox/pygeobuf/blob/master/test/fixtures/feature.json
