### ISSUE TITLE
python3 'long' error

### ISSUE THREAD

**Issue by bertrandmd** [mapbox/pygeobuf#31]
Hello, 

I have an error, when running pygeobuf with python3.

It's because of the use of `long` in [this line](https://github.com/mapbox/pygeobuf/blob/master/geobuf/encode.py#L159)

thanks

**Comment by jlaine** [comment]
Using six.integer_types would solve the problem while maintaining py2 compatibility. Would you accept a pull request ?

**Comment by alpha-beta-soup** [comment]
Just encountered this issue also. @jlaine's fix addresses the issue for my use case. :+1:

**Comment by sgillies** [comment]
Fixed via 307f3fa
