### ISSUE TITLE
1.1.1 release

### ISSUE THREAD

**Issue by sgillies** [mapbox/pygeobuf#34]
Bug fixes #33.

**Comment by jlaine** [comment]
Can I suggest version 1.1.1 be released as-is and uploaded to pypi? I think in 2017, fixing py3 compatibility warrants a release to itself :)

Pushing out another release as soon as some more interesting fixes land is cheap, and I'd be more than happy to help out as previously stated.

**Comment by jlaine** [comment]
Hi Sean, sorry to nag but would it be possible to tag/upload 1.1.1 to pypi please?

**Comment by sgillies** [comment]
1.1.1 coming up.

**Comment by sgillies** [comment]
Done: https://pypi.python.org/pypi/geobuf/1.1.1. Thanks for the nudge, @jlaine.
